<?php
echo "<html>\n";
echo "   <head>\n";
echo "       <title>wumiaos</title>\n";
echo "       <meta charset=\"utf-8\">\n";
echo "       <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n";
echo "       <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0\">\n";
echo "       <script src=\"./jquery.min.js\"></script>\n";
echo "   </head>\n";
echo "   <body>\n";
echo "       <img id=\"rand\" src=\"/api01.php\" onclick=\"imgKick01()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick01(){\n";
echo "               var url = \"/api01.php?v=\"+Math.round(Math.random()*10000);\n";
echo "               $('#rand').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br><br>\n";
echo "       <img id=\"rand1\" src=\"/api02.php\" onclick=\"imgKick02()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick02(){\n";
echo "               var url = \"/api02.php?v=\"+Math.round(Math.random()*10000);\n";
echo "               $('#rand1').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br><br>\n";
echo "       <img id=\"rand2\" src=\"/api03.php\" onclick=\"imgKick03()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick03(){\n";
echo "               var url = \"/api03.php?v=\"+Math.round(Math.random()*10000);\n";
echo "               $('#rand2').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br><br>\n";
echo "       <img id=\"rand3\" src=\"/api04.php\" onclick=\"imgKick04()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick04(){\n";
echo "               var url = \"/api04.php?v=\"+Math.round(Math.random()*10000);\n";
echo "               $('#rand3').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br><br>\n";
echo "       <img id=\"rand4\" src=\"/api05.php\" onclick=\"imgKick05()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick05(){\n";
echo "               var url = \"/api05.php?v=\"+Math.round(Math.random()*10000);\n";
echo "               $('#rand4').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "   </body>\n";
echo "/html>\n";
?>